---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - repos.yaml
  - apps.yaml
  - crossplane-providers.yaml
  - aws-provider-config.yaml
  - crossplane-compositions.yaml
  - crossplane